app/admin/views.py
"""Views for the admin."""
from flask import flash
from flask import url_for
from flask import request
from flask import redirect
from flask import Blueprint
from flask import render_template

from app.admin.models import User

from app.admin.forms import LoginForm
from app.admin.forms import RegisterForm

from flask_login import login_user
from flask_login import logout_user

from flask_bcrypt import Bcrypt

from flask_wtf.csrf import generate_csrf

admin_bp = Blueprint(
    "admin", __name__, template_folder="templates", static_folder="static"
)

bcrypt = Bcrypt()


@admin_bp.route("/users/register", methods=["GET", "POST"])
def register():
    """Register new user

    Atributes:
    - name (StringField): The name of the user.
    - email (StringField): The email of the user.
    - password (PasswordField): The password of the user.
    - submit (SubmitField): The button to submit the form and register the user.

    Returns:
    - A redirect to the index page.
    """
    form = RegisterForm()
    if form.validate_on_submit():
        name: str = form.name.data
        email: str = form.email.data
        password: str = form.password.data

        csrf_token: str = generate_csrf()

        try:
            User.create(name=name,
                        email=email,
                        password=bcrypt.generate_password_hash(password))

        except User.Exist:
            User.get(User.email == email)
            flash("Email ya registrado.")
            return render_template("index.index",
                                   form=form,
                                   csrf_token=csrf_token)

    else:
        return render_template("register.html", form=form)


@admin_bp.route("/users/login", methods=["GET", "POST"])
def login():
    """Login form. Validates that username matches, and password is correct.

    Atributes:
    - email (StringField): The email of the user.
    - password (PasswordField): The password of the user.
    - submit (SubmitField): The button to submit the form and login the user.

    Returns:
    - A redirect to the index page.
    """
    form = LoginForm()
    if form.validate_on_submit():
        email: str = form.email.data
        password: str = form.password.data

        csrf_token: str = generate_csrf()

        try:
            user = User.get(User.email == email)
            if bcrypt.check_password_hash(user.password, password):
                login_user(user)
                flash("Logged in successfully.")
                return redirect(url_for("index.index"))

        except User.DoesNotExist:
            flash("Email o Password incorrectos.")
            return render_template("login.html",
                                   form=form,
                                   csrf_token=csrf_token)

    else:
        return render_template("login.html", form=form)


@admin_bp.route("/logout")
def logout():
    """Logout Form

    Atributes:
    - id (int): The id of the user to update.

    Returns:
    - A redirect to the index page.
    """
    logout_user()

    return redirect(url_for("index.index"))


@admin_bp.route("/users/update/<int:id>", methods=["GET", "POST"])
def update_user(id):
    """Update user

    Atributes:
    - id (int): The id of the user to update.

    Returns:
    - A redirect to the index page.
    """
    if request.method == "POST":
        user = User.update(
            name=request.form["name"],
            email=request.form["email"],
            password=request.form["password"],
        ).where(User.id == id)

        user.execute()

        return redirect(url_for("index.index"))

    return render_template("edit.html")


@admin_bp.route("/users/update/<int:id>", methods=["GET", "POST"])
def delete_user(id):
    """Delete user

    Atributes:
    - id (int): The id of the user to delete.

    Returns:
    - A redirect to the index page.
    """
    user = User.delete().where(User.id == id)

    user.execute()

    return redirect(url_for("index.index"))

app/index/templates/first.html
<section class="posts-container">
    <div>
        <div class="posts-title">
            <h2 class="post-subtitle">Entradas</h2>
            {% if current_user.is_authenticated %}
            <a class="post-link-new" href="posts/create">Nueva Entrada</a>
            {% endif %}
        </div>
        <div class="card">
            {% for post in posts %}
            <div class="card-container">
                    <ul class="card-full">
                        <div class="card-image-container">
                            <img class="card-image" src="{{post.route}}" alt="Imagen Post">
                        </div>
                        <div class="card-content">
                            <div>
                                <li class="post-title">{{ post.title }}</li>
                            </div>
                            <br>
                            <div class="post-content">
                                <li class="card-li">{{ post.content|safe }}</li>
                            </div>
                            <br>
                            <div class="post-bot">
                                <a class="card-link" href="post/{{post.id}}"> Ver más... </a>
                            </div>
                        </div>
                    </ul>
            </div>
            {% endfor %}
        </div>
    </div>
    <aside class="aside-container">
        <div class="aside-content">
            <div class="spotify">
                <iframe src="https://open.spotify.com/embed/playlist/06SI5DNSTRagHmuPHRBru3?utm_source=generator&theme=0" width="225px" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
            </div>
            <div class="aside-search">
                <label class="aside-search-title" for="site-search">Buscar en el sitio:</label>
                <input type="search" id="site-search" name="q">
                <button class="aside-buttom">Buscar</button>
            </div>
            <div class="category-container">
                <div>
                    <h3 class="category-title">Etiquetas</h3>
                </div>
                <div class="category-content">
                    {% for tag in tags %}
                    <ul>
                        <li class="tags-list">
                            <a class="link-tag-full" href="tags/{{ tag.name_tag }}">{{ tag.name_tag }}</a>
                        </li>
                    </ul>
                    {% endfor %}
                </div>
            </div>
        </div>
    </aside>
</section>

app/index/templates/index.html
{% extends "layout.html" %}

{% block content %}

    <section class="hero-container">

        <div class="hero">
            <div class="hero-text">
                <h2>Snake CODE</h2>
                <p>Blog Desarrollado y Enfocado al Lenguaje de Programación Python,<br>
                    <br> sus Frameworks y sus Librerías.</p>
            </div>
        </div>  

    </section>

{% include 'first.html' %}

{% endblock %}

app/index/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{url_for('static', filename='css/normalize.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/cef0e935a9.js" crossorigin="anonymous"></script>
    <title>Snake CODE</title>
</head>
<body>
    <nav class="nav">
        <div class="nav-logo">
            <a href="{{url_for('index.index')}}">
                <img class="nav-image" src="https://res.cloudinary.com/duckwaaai/image/upload/f_auto,q_auto/v1/BlogProject/Logos/jy44cakusetxgoxkaxwl" alt="logotipo">
            </a>
        </div>
        <div class="nav-menu">
            {% if current_user.is_authenticated %}
            <ul>
                {% for user in users %}
                <li>Bienvenido: <strong>{{ user.name }}</strong></li>
                {% endfor %}
                <li><a href="">Hola, <strong>{{ current_user.name }}</strong></a></li>
                <li><a href="{{url_for('index.index')}}">Inicio</a></li>
                <li><a href="{{url_for('admin.logout')}}">Cerrar Sesión</a></li>
            </ul>
            {% else %}
            <ul>
                <li><a href="{{url_for('index.index')}}">Inicio</a></li>
                <li><a href="{{url_for('admin.login')}}">Iniciar Sesión</a></li>
            </ul>
            {% endif %}
        </div>
    </nav>
    <section>{% block content %}{% endblock %}</section>
    <footer class="footer-container">
        <div class="footer">
            <div class="center full-width">
                <div class="row">
                    <h3>CONTÁCTAME</h3>
                </div>
            </div>
            <div class="center full-width">
                <div class="row">
                    <p>No olvides seguirme en mis Redes Sociales</p>
                </div>
            </div>
            <div class="center full-sidth social-links">
                <div class="row">
                    <a target="_blank" href="https://www.facebook.com/Jorge-Garcia-Dev-105078822218513">
                        <img class="social" src="https://res.cloudinary.com/duckwaaai/image/upload/f_auto,q_auto/v1/BlogProject/Logos/lwutjqbv5h8rki6behqg" alt="Logo Facebook">
                    </a>
                </div>
                <div class="row">
                    <a target="_blank" href="https://twitter.com/JorgeGarcia_Dev">
                        <img class="social" src="https://res.cloudinary.com/duckwaaai/image/upload/f_auto,q_auto/v1/BlogProject/Logos/sylaio0mfwimxpbivt3m" alt="Logo Twitter">
                    </a>
                </div>
                <div class="row">
                    <a target="_blank" href="https://www.linkedin.com/in/jorgegarcia-dev">
                        <img class="social" src="https://res.cloudinary.com/duckwaaai/image/upload/f_auto,q_auto/v1/BlogProject/Logos/l3yozwujrv0azg5khavd" alt="Logo Linkedin">
                    </a>
                </div>
                <div class="row">
                    <a target="_blank" href="https://github.com/JorgeGarcia-Dev">
                        <img class="social" src="https://res.cloudinary.com/duckwaaai/image/upload/f_auto,q_auto/v1/BlogProject/Logos/f3wwy3tpi2rzpen8xpbk" alt="Logo GitHub">
                    </a>
                </div>
            </div>
            <div class="made-width">
                <div class="row">
                    <p class="love">Development By_ <span>Jorge Garcia Dev</span></p>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>